//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.PhieuMuon_Sachs = new HashSet<PhieuMuon_Sachs>();
            this.TheLoais = new HashSet<TheLoai>();
        }
    
        public int ID { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> ID_TacGia { get; set; }
        public System.DateTime NgayXB { get; set; }
        public string MoTa { get; set; }
        public int SoLuong { get; set; }
        public double DonGia { get; set; }
        public string ID_NhaPhanPhoi { get; set; }
        public byte[] AnhSach { get; set; }
    
        public virtual NhaPhanPhoi NhaPhanPhoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon_Sachs> PhieuMuon_Sachs { get; set; }
        public virtual TacGia TacGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheLoai> TheLoais { get; set; }
    }
}
